version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "1337:3000"
    environment:
      - NODE_ENV=production