services:
  web:
    image: ghcr.io/init-sggw/icc-web:${BUILD_ENV:-production}
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-production}

  admin:
    image: ghcr.io/init-sggw/icc-admin:${BUILD_ENV:-production}
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-production}
        - ADMIN_API_KEY=${ADMIN_API_KEY:-}

  backend:
    image: ghcr.io/init-sggw/icc-backend:${BUILD_ENV:-production}
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env.development.local
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=production
