services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "1337:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env.development.local
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=production
